import {guard,call,renderNav,toast,fmt,esc} from './app.js';
const u=await guard();renderNav('profile');
async function load(){try{const [stats,ws,users,tasks,cfg,completions]=await Promise.all([call('adminStats'),call('adminListWithdrawals',{limit:50}),call('adminListUsers',{limit:50}),call('adminListTasks'),call('adminGetConfig'),call('adminListTaskCompletions')]);document.querySelector('#stats').innerHTML=`<div class="stat"><span>Users</span><b>${stats.data.users}</b></div><div class="stat"><span>Withdrawals</span><b>${stats.data.withdrawals}</b></div><div class="stat"><span>Coins issued</span><b>${stats.data.coinsIssued}</b></div><div class="stat"><span>Pending coins</span><b>${stats.data.pendingCoins}</b></div>`;renderWithdrawals(ws.data);renderUsers(users.data);renderTasks(tasks.data);renderConfig(cfg.data);renderCompletions(completions.data)}catch(e){document.querySelector('#adminError').textContent=e.message||'Not authorized'}}
function renderWithdrawals(rows){const el=document.querySelector('#wrows');el.innerHTML=rows.map(w=>`<tr><td>${esc(w.id)}</td><td>${esc(w.uid)}</td><td>${w.coins}</td><td>${esc(w.status)}</td><td>${w.status==='pending'?`<button data-id="${w.id}" data-status="approved" class="btn btn-secondary small approve">Approve</button> <button data-id="${w.id}" data-status="rejected" class="btn btn-danger small approve">Reject</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">No withdrawals</td></tr>';el.querySelectorAll('.approve').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await call('adminUpdateWithdrawal',{withdrawalId:b.dataset.id,status:b.dataset.status});toast('Updated');load()}catch(e){toast(e.message)}finally{b.disabled=false}})}
function renderUsers(rows){document.querySelector('#urows').innerHTML=rows.map(x=>`<tr><td>${esc(x.name||'')}</td><td>${esc(x.email||'')}</td><td>${x.coins||0}</td><td>${x.disabled?'Disabled':'Active'}</td><td><button data-uid="${x.uid}" class="btn btn-danger small disable">${x.disabled?'Enable':'Disable'}</button></td></tr>`).join('')||'<tr><td colspan="5">No users</td></tr>';document.querySelectorAll('.disable').forEach(b=>b.onclick=async()=>{await call('adminSetUserDisabled',{uid:b.dataset.uid,disabled:b.textContent==='Disable'});load()})}
function renderTasks(rows){document.querySelector('#tasks').innerHTML=rows.map(t=>`<div class="list-item"><div><b>${esc(t.title)}</b><div class="small muted">${t.rewardCoins} coins · ${esc(t.status)}</div></div></div>`).join('')||'<div class="muted">No tasks</div>'}
function renderConfig(c){document.querySelector('#coinsPerRupee').value=c.coinsPerRupee||100;document.querySelector('#adCoins').value=c.rewardedAdCoins||25;document.querySelector('#minWithdrawal').value=c.minWithdrawalCoins||1000;document.querySelector('#refReward').value=c.referralRewardCoins||100;document.querySelector('#refQual').value=c.referralQualifyingCoins||500}
document.querySelector('#configForm').onsubmit=async e=>{e.preventDefault();try{await call('adminSetConfig',{coinsPerRupee:Number(coinsPerRupee.value),rewardedAdCoins:Number(adCoins.value),minWithdrawalCoins:Number(minWithdrawal.value),referralRewardCoins:Number(refReward.value),referralQualifyingCoins:Number(refQual.value)});toast('Configuration saved')}catch(x){toast(x.message)}};load();

document.querySelector('#taskForm').onsubmit=async e=>{e.preventDefault();try{await call('adminCreateTask',{title:taskTitle.value,description:taskDescription.value,rewardCoins:Number(taskReward.value),dailyLimit:Number(taskLimit.value),completionMode:taskMode.value,status:'active'});e.target.reset();toast('Task created');load()}catch(x){toast(x.message)}};
